// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// import 'firebase_options.dart';
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEWVoZWeYOQCtDhz_R2iUU6MyFhjWG9gE',
    appId: '1:709985113409:web:be43baab4682d103f1fdc0',
    messagingSenderId: '709985113409',
    projectId: 'sportify2-225a5',
    authDomain: 'sportify2-225a5.firebaseapp.com',
    storageBucket: 'sportify2-225a5.appspot.com',
    measurementId: 'G-BXBT853619',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBox5RQo72F91lUz5g3jB0WASElIMs46P8',
    appId: '1:709985113409:android:1749174ffb85b1f6f1fdc0',
    messagingSenderId: '709985113409',
    projectId: 'sportify2-225a5',
    storageBucket: 'sportify2-225a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD78IdmF1nxVv3CCm5Fwz8_LDbReViXrZY',
    appId: '1:709985113409:ios:e916a6e70612d00af1fdc0',
    messagingSenderId: '709985113409',
    projectId: 'sportify2-225a5',
    storageBucket: 'sportify2-225a5.appspot.com',
    iosClientId:
        '709985113409-grmik5o8ciuhkmkp50akppfqmj3i4va5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD78IdmF1nxVv3CCm5Fwz8_LDbReViXrZY',
    appId: '1:709985113409:ios:a6dc01b624e12eddf1fdc0',
    messagingSenderId: '709985113409',
    projectId: 'sportify2-225a5',
    storageBucket: 'sportify2-225a5.appspot.com',
    iosClientId:
        '709985113409-5sctnognc1gchsiiga52qjoieauo0s16.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportifyapp.RunnerTests',
  );
}
